### ISSUE TITLE
Unable to find option to change DB to mysql

### ISSUE THREAD

**Issue by cshekhar17** [Shahzayb/vuquiz#5]
Hi Shahzayb,

I am trying to change the DB to mysql but not able to find where to make to change. Can you please help in this ?

**Comment by Shahzayb** [comment]
> Hi Shahzayb,
> 
> I am trying to change the DB to mysql but not able to find where to make to change. Can you please help in this ?

https://www.youtube.com/watch?v=K2ohZaoR6Ko&ab_channel=SpringFrameworkGuru
